const fs = require("fs");
let p = "C:/Users/faiz/.gemini/antigravity-ide/brain/13363e8a-ca2d-4164-b630-8848e72db34a/task.md";
let c = fs.readFileSync(p, "utf8");
c = c.replace(/- `\[/\]` 2\. Update Admin Panel/, "- `[x]` 2. Update Admin Panel");
c = c.replace(/- `\[ \]` Update `destinations` form/, "- `[x]` Update `destinations` form");
c = c.replace(/- `\[ \]` Update `news_articles` form/, "- `[x]` Update `news_articles` form");
c = c.replace(/- `\[ \]` Update `hero_sliders` form/, "- `[x]` Update `hero_sliders` form");
c = c.replace(/- `\[ \]` Update `galleries` form/, "- `[x]` Update `galleries` form");
c = c.replace(/- `\[ \]` Update `categories` form/, "- `[x]` Update `categories` form");
c = c.replace(/- `\[ \]` Update `events` form/, "- `[x]` Update `events` form");
c = c.replace(/- `\[ \]` 3\. Update Web Frontend/, "- `[/]` 3. Update Web Frontend");
fs.writeFileSync(p, c, "utf8");
