const fs = require("fs");
let p = "C:/Users/faiz/.gemini/antigravity-ide/brain/13363e8a-ca2d-4164-b630-8848e72db34a/task.md";
let c = fs.readFileSync(p, "utf8");
c = c.replace(/- `\[/\]` 3\. Update Web Frontend/, "- `[x]` 3. Update Web Frontend");
c = c.replace(/- `\[ \]` Update `page\.tsx` \(Home\)/, "- `[x]` Update `page.tsx` (Home)");
c = c.replace(/- `\[ \]` Update `destinasi\/\[slug\]\/page\.tsx`/, "- `[x]` Update `destinasi/[slug]/page.tsx`");
c = c.replace(/- `\[ \]` Update `berita\/\[slug\]\/page\.tsx`/, "- `[x]` Update `berita/[slug]/page.tsx`");
c = c.replace(/- `\[ \]` Update `CategoryListingUI\.tsx`/, "- `[x]` Update `CategoryListingUI.tsx`");
c = c.replace(/- `\[ \]` Update `CategoryUI` and `Events` mapping/, "- `[x]` Update `CategoryUI` and `Events` mapping");
fs.writeFileSync(p, c, "utf8");
